name: cd

on:
  push:
    branches:
      - main

jobs:
  cd:
    runs-on: ${{ matrix.os }}

    environment: production
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [20]

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup node env 🏗
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node }}
          check-latest: true
          cache: 'yarn'

      - name: Install dependencies 👨🏻‍💻
        run: yarn

      - name: Generate
        run: yarn run generate
        env:
          BASE_URL: /board-game-calendar/
          NODE_ENV: production
          G_API_KEY: ${{secrets.G_API_KEY}}
          G_APP_ID: ${{secrets.G_APP_ID}}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
